"""
This file is part of CLIMADA.

Copyright (C) 2017 ETH Zurich, CLIMADA contributors listed in AUTHORS.

CLIMADA is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free
Software Foundation, version 3.

CLIMADA is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with CLIMADA. If not, see <https://www.gnu.org/licenses/>.

---

Define constants.
"""

__all__ = ['SYSTEM_DIR',
           'DEMO_DIR',
           'ENT_DEMO_TODAY',
           'ENT_DEMO_FUTURE',
           'HAZ_DEMO_MAT',
           'HAZ_DEMO_FL',
           'HAZ_DEMO_FLDDPH',
           'HAZ_DEMO_FLDFRC',
           'ENT_TEMPLATE_XLS',
           'HAZ_TEMPLATE_XLS',
           'ONE_LAT_KM',
           'EARTH_RADIUS_KM',
           'GLB_CENTROIDS_MAT',
           'GLB_CENTROIDS_NC',
           'ISIMIP_GPWV3_NATID_150AS',
           'NATEARTH_CENTROIDS',
           'DEMO_GDP2ASSET',
           'RIVER_FLOOD_REGIONS_CSV',
           'TC_ANDREW_FL',
           'HAZ_DEMO_H5',
           'EXP_DEMO_H5',
           'WS_DEMO_NC']

from climada.util.constants import (DEMO_DIR, SYSTEM_DIR, ENT_DEMO_TODAY, ENT_DEMO_FUTURE,
                                    HAZ_DEMO_MAT, HAZ_DEMO_FL, ENT_TEMPLATE_XLS, HAZ_TEMPLATE_XLS, ONE_LAT_KM, EARTH_RADIUS_KM,
                                    GLB_CENTROIDS_MAT, GLB_CENTROIDS_NC, ISIMIP_GPWV3_NATID_150AS, NATEARTH_CENTROIDS,
                                    RIVER_FLOOD_REGIONS_CSV, TC_ANDREW_FL, HAZ_DEMO_H5, EXP_DEMO_H5, WS_DEMO_NC)


HAZ_DEMO_FLDDPH = DEMO_DIR.joinpath('flddph_2000_DEMO.nc')
"""NetCDF4 Flood depth from isimip simulations"""

HAZ_DEMO_FLDFRC = DEMO_DIR.joinpath('fldfrc_2000_DEMO.nc')
"""NetCDF4 Flood fraction from isimip simulations"""

DEMO_GDP2ASSET = DEMO_DIR.joinpath('gdp2asset_CHE_exposure.nc')
"""Exposure demo file for GDP2Asset"""

DICT_SPEEDS = {'BTN': 38.0,
               'NPL': 40.0,
               'TLS': 40.0,
               'BGD': 41.0,
               'HTI': 41.0,
               'NIC': 46.0,
               'RWA': 47.0,
               'BOL': 50.0,
               'LKA': 50.0,
               'GIN': 50.0,
               'BDI': 51.0,
               'VNM': 51.0,
               'MDG': 51.0,
               'TTO': 51.0,
               'TJK': 52.0,
               'PHL': 52.0,
               'GMB': 53.0,
               'GTM': 53.0,
               'CRI': 55.0,
               'IDN': 55.0,
               'NGA': 55.0,
               'YEM': 55.0,
               'KHM': 55.0,
               'GHA': 56.0,
               'SLV': 56.0,
               'MNG': 56.0,
               'HND': 56.0,
               'CMR': 56.0,
               'TZA': 57.0,
               'AFG': 57.0,
               'BIH': 57.0,
               'ARM': 57.0,
               'COL': 57.0,
               'KEN': 57.0,
               'IND': 58.0,
               'SOM': 58.0,
               'SSD': 59.0,
               'PNG': 59.0,
               'GUY': 59.0,
               'MNE': 59.0,
               'LSO': 60.0,
               'ECU': 60.0,
               'LAO': 60.0,
               'LBN': 60.0,
               'GNB': 60.0,
               'GAB': 60.0,
               'ETH': 61.0,
               'KGZ': 61.0,
               'CAF': 73.0,
               'JAM': 61.0,
               'COG': 62.0,
               'ERI': 62.0,
               'PER': 62.0,
               'TGO': 63.0,
               'DRC': 63.0,
               'BFA': 63.0,
               'BEN': 63.0,
               'TCD': 63.0,
               'UGA': 64.0,
               'GEO': 64.0,
               'SLE': 64.0,
               'ALB': 65.0,
               'XKO': 65.0,
               'SUR': 65.0,
               'LBR': 66.0,
               'MDA': 67.0,
               'BLZ': 67.0,
               'PRY': 67.0,
               'NER': 69.0,
               'DJI': 69.0,
               'SWZ': 69.0,
               'SEN': 71.0,
               'UZB': 71.0,
               'MMR': 71.0,
               'SYR': 72.0,
               'KAZ': 72.0,
               'BRA': 72.0,
               'MLI': 72.0,
               'PAN': 72.0,
               'SDN': 72.0,
               'ROU': 73.0,
               'ZMB': 73.0,
               'NOR': 73.0,
               'GNQ': 74.0,
               'DOM': 74.0,
               'MKD': 74.0,
               'MWI': 75.0,
               'UKR': 75.0,
               'RUS': 76.0,
               'CYP': 76.0,
               'JOR': 77.0,
               'THA': 77.0,
               'LVA': 77.0,
               'ISL': 77.0,
               'MRT': 77.0,
               'AGO': 78.0,
               'CUB': 78.0,
               'MOZ': 78.0,
               'TUN': 78.0,
               'CIV': 78.0,
               'PRI': 78.0,
               'DNK': 78.0,
               'IRQ': 79.0,
               'TKM': 79.0,
               'AZE': 80.0,
               'ARE': 80.0,
               'EST': 81.0,
               'JPN': 81.0,
               'QAT': 82.0,
               'URY': 82.0,
               'NZL': 83.0,
               'EGY': 83.0,
               'ZWE': 83.0,
               'FIN': 83.0,
               'VEN': 83.0,
               'ISR': 84.0,
               'KWT': 85.0,
               'BLR': 85.0,
               'PAK': 86.0,
               'CHE': 87.0,
               'NLD': 87.0,
               'GBR': 87.0,
               'BGR': 88.0,
               'BRN': 88.0,
               'DZA': 88.0,
               'IRL': 88.0,
               'LTU': 89.0,
               'LBY': 90.0,
               'CHN': 90.0,
               'SVN': 90.0,
               'MEX': 90.0,
               'ARG': 91.0,
               'BWA': 91.0,
               'TWN': 91.0,
               'MYS': 92.0,
               'POL': 92.0,
               'CHL': 92.0,
               'BEL': 92.0,
               'GRC': 93.0,
               'KOR': 93.0,
               'TUR': 93.0,
               'SVK': 93.0,
               'SWE': 94.0,
               'IRN': 94.0,
               'SRB': 94.0,
               'ITA': 95.0,
               'MAR': 95.0,
               'AUS': 96.0,
               'AUT': 96.0,
               'HUN': 96.0,
               'DEU': 97.0,
               'CZE': 98.0,
               'HRV': 98.0,
               'NAM': 99.0,
               'ZAF': 100.0,
               'OMN': 102.0,
               'ESP': 103.0,
               'FRA': 105.0,
               'CAN': 106.0,
               'SAU': 106.0,
               'PRT': 106.0,
               'USA': 107.0,
               'other': 73.0}

"""
World Bank Income Group Classifications - 2021
"""
DICT_INCCLASS = {'ABW': 1.0,
                 'AFG': 4.0,
                 'AGO': 3.0,
                 'ALB': 2.0,
                 'AND': 1.0,
                 'ARE': 1.0,
                 'ARG': 2.0,
                 'ARM': 2.0,
                 'ASM': 2.0,
                 'ATG': 1.0,
                 'AUS': 1.0,
                 'AUT': 1.0,
                 'AZE': 2.0,
                 'BDI': 4.0,
                 'BEL': 1.0,
                 'BEN': 3.0,
                 'BFA': 4.0,
                 'BGD': 3.0,
                 'BGR': 2.0,
                 'BHR': 1.0,
                 'BHS': 1.0,
                 'BIH': 2.0,
                 'BLR': 2.0,
                 'BLZ': 3.0,
                 'BMU': 1.0,
                 'BOL': 3.0,
                 'BRA': 2.0,
                 'BRB': 1.0,
                 'BRN': 1.0,
                 'BTN': 3.0,
                 'BWA': 2.0,
                 'CAF': 4.0,
                 'CAN': 1.0,
                 'CHE': 1.0,
                 'Channel Islands': 1.0,
                 'CHL': 1.0,
                 'CHN': 2.0,
                 'CIV': 3.0,
                 'CMR': 3.0,
                 'DRC': 4.0,
                 'COG': 3.0,
                 'COL': 2.0,
                 'COM': 3.0,
                 'CPV': 3.0,
                 'CRI': 2.0,
                 'CUB': 2.0,
                 'CUW': 1.0,
                 'CYM': 1.0,
                 'CYP': 1.0,
                 'CZE': 1.0,
                 'DEU': 1.0,
                 'DJI': 3.0,
                 'DMA': 2.0,
                 'DNK': 1.0,
                 'DOM': 2.0,
                 'DZA': 3.0,
                 'ECU': 2.0,
                 'EGY': 3.0,
                 'ERI': 4.0,
                 'ESP': 1.0,
                 'EST': 1.0,
                 'ETH': 4.0,
                 'FIN': 1.0,
                 'FJI': 2.0,
                 'FRA': 1.0,
                 'FRO': 1.0,
                 'FSM': 3.0,
                 'GAB': 2.0,
                 'GBR': 1.0,
                 'GEO': 2.0,
                 'GHA': 3.0,
                 'GIB': 1.0,
                 'GIN': 4.0,
                 'GMB': 4.0,
                 'GNB': 4.0,
                 'GNQ': 2.0,
                 'GRC': 1.0,
                 'GRD': 2.0,
                 'GRL': 1.0,
                 'GTM': 2.0,
                 'GUM': 1.0,
                 'GUY': 2.0,
                 'HKG': 1.0,
                 'HND': 3.0,
                 'HRV': 1.0,
                 'HTI': 3.0,
                 'HUN': 1.0,
                 'IDN': 3.0,
                 'IMN': 1.0,
                 'IND': 3.0,
                 'IRL': 1.0,
                 'IRN': 3.0,
                 'IRQ': 2.0,
                 'ISL': 1.0,
                 'ISR': 1.0,
                 'ITA': 1.0,
                 'JAM': 2.0,
                 'JOR': 2.0,
                 'JPN': 1.0,
                 'KAZ': 2.0,
                 'KEN': 3.0,
                 'KGZ': 3.0,
                 'KHM': 3.0,
                 'KIR': 3.0,
                 'KNA': 1.0,
                 'KOR': 1.0,
                 'KWT': 1.0,
                 'LAO': 3.0,
                 'LBN': 2.0,
                 'LBR': 4.0,
                 'LBY': 2.0,
                 'LCA': 2.0,
                 'LIE': 1.0,
                 'LKA': 3.0,
                 'LSO': 3.0,
                 'LTU': 1.0,
                 'LUX': 1.0,
                 'LVA': 1.0,
                 'MAC': 1.0,
                 'MAF': 1.0,
                 'MAR': 3.0,
                 'MCO': 1.0,
                 'MDA': 2.0,
                 'MDG': 4.0,
                 'MDV': 2.0,
                 'MEX': 2.0,
                 'MHL': 2.0,
                 'MKD': 2.0,
                 'MLI': 4.0,
                 'MLT': 1.0,
                 'MMR': 3.0,
                 'MNE': 2.0,
                 'MNG': 3.0,
                 'MNP': 1.0,
                 'MOZ': 4.0,
                 'MRT': 3.0,
                 'MUS': 2.0,
                 'MWI': 4.0,
                 'MYS': 2.0,
                 'NAM': 2.0,
                 'NCL': 1.0,
                 'NER': 4.0,
                 'NGA': 3.0,
                 'NIC': 3.0,
                 'NLD': 1.0,
                 'NOR': 1.0,
                 'NPL': 3.0,
                 'NRU': 1.0,
                 'NZL': 1.0,
                 'OMN': 1.0,
                 'PAK': 3.0,
                 'PAN': 2.0,
                 'PER': 2.0,
                 'PHL': 3.0,
                 'PLW': 1.0,
                 'PNG': 3.0,
                 'POL': 1.0,
                 'PRI': 1.0,
                 'PRK': 4.0,
                 'PRT': 1.0,
                 'PRY': 2.0,
                 'PSE': 3.0,
                 'PYF': 1.0,
                 'QAT': 1.0,
                 'ROU': 2.0,
                 'RUS': 2.0,
                 'RWA': 4.0,
                 'SAU': 1.0,
                 'SDN': 4.0,
                 'SEN': 3.0,
                 'SGP': 1.0,
                 'SLB': 3.0,
                 'SLE': 4.0,
                 'SLV': 3.0,
                 'SMR': 1.0,
                 'SOM': 4.0,
                 'SRB': 2.0,
                 'SSD': 4.0,
                 'STP': 3.0,
                 'SUR': 2.0,
                 'SVK': 1.0,
                 'SVN': 1.0,
                 'SWE': 1.0,
                 'SWZ': 3.0,
                 'SXM': 1.0,
                 'SYC': 1.0,
                 'SYR': 4.0,
                 'TCA': 1.0,
                 'TCD': 4.0,
                 'TGO': 4.0,
                 'THA': 2.0,
                 'TJK': 3.0,
                 'TKM': 2.0,
                 'TLS': 3.0,
                 'TON': 2.0,
                 'TTO': 1.0,
                 'TUN': 3.0,
                 'TUR': 2.0,
                 'TUV': 2.0,
                 'TZA': 3.0,
                 'UGA': 4.0,
                 'UKR': 3.0,
                 'URY': 1.0,
                 'USA': 1.0,
                 'UZB': 3.0,
                 'VCT': 2.0,
                 'VEN': None,
                 'VGB': 1.0,
                 'VIR': 1.0,
                 'VNM': 3.0,
                 'VUT': 3.0,
                 'WSM': 3.0,
                 'XKO': 2.0,
                 'YEM': 4.0,
                 'ZAF': 2.0,
                 'ZMB': 3.0,
                 'ZWE': 3.0}
