pipeline {
  agent any

  stages {
    stage('ci') {
      parallel {

        stage('lint') {
          steps {
            sh 'bash script/jeknins/branches/run_lint.sh'
            discoverGitReferenceBuild referenceJob: 'petals_branches/develop'
            recordIssues tools: [pyLint(pattern: 'pylint.log')]
          }
        }

        stage('unit_test') {
          steps {
            sh 'bash script/jenkins/branches/run_unittest.sh'
          }
        }

      }
    }
  }

  post {
    always {
      junit 'tests_xml/*.xml'
      cobertura coberturaReportFile: 'coverage.xml'
    }
  }
}
