pipeline {
  agent any

  stages {
    stage('ci') {
      parallel {

        stage('lint') {
          steps {
            sh 'bash script/jenkins/branches/run_lint.sh'
            discoverGitReferenceBuild referenceJob: 'petals_branches/develop'
            recordIssues tools: [pyLint(pattern: 'pylint.log')]
          }
        }

        stage('unit_test') {
          steps {
            sh 'bash script/jenkins/branches/run_unittest.sh'
          }
        }

      }
    }
  }

  post {
    always {
      junit 'tests_xml/*.xml'
      recordCoverage(
        qualityGates: [[
          baseline: 'PROJECT_DELTA',
          metric: 'LINE',
          threshold: 0.0
        ]],
        tools: [[
          parser: 'COBERTURA',
          pattern: 'coverage.xml'
        ]]
      )
    }
  }
}
